const Map<String, String> _fieldLabels = {
  'teacher.fullName': 'Ad Soyad',
  'teacher.firstName': 'Ad',
  'teacher.lastName': 'Soyad',
  'teacher.branch': 'Branş',
  'teacher.title': 'Unvan',
  'teacher.phone': 'Telefon',
  'teacher.email': 'E-posta',
  'teacher.registrationNo': 'Sicil No',
  'teacher.serviceYears': 'Hizmet Yılı',
  'teacher.employmentType': 'İstihdam Türü',
  'teacher.nationalId': 'T.C. Kimlik No',
  'school.name': 'Okul Adı',
  'school.code': 'Okul Kodu',
  'school.city': 'İl',
  'school.district': 'İlçe',
  'school.address': 'Okul Adresi',
  'school.principalName': 'Okul Müdürü',
  'document.date': 'Tarih',
  'document.subject': 'Konu',
  'document.number': 'Evrak No',
  'document.description': 'Açıklama',
  'document.startDate': 'Başlangıç Tarihi',
  'document.endDate': 'Bitiş Tarihi',
  'student.fullName': 'Öğrenci Adı Soyadı',
  'student.className': 'Sınıf/Şube',
  'parent.fullName': 'Veli Adı Soyadı',
  'meeting.date': 'Toplantı Tarihi',
  'meeting.topic': 'Toplantı Konusu',
  'meeting.decisions': 'Alınan Kararlar',
  'leave.startDate': 'İzin Başlangıç Tarihi',
  'leave.endDate': 'İzin Bitiş Tarihi',
  'lesson.subject': 'Ders Adı',
  'lesson.gradeLevel': 'Sınıf/Şube',
  'lesson.topic': 'Konu',
  'plan.content': 'Konular ve Kazanımlar',
};

String fieldLabel(String key) => _fieldLabels[key] ?? key;
