const Map<String, String> _fieldLabels = {
  'teacher.fullName': 'Ad Soyad',
  'teacher.firstName': 'Ad',
  'teacher.lastName': 'Soyad',
  'teacher.branch': 'Branş',
  'teacher.title': 'Unvan',
  'teacher.phone': 'Telefon',
  'teacher.email': 'E-posta',
  'teacher.registrationNo': 'Sicil No',
  'teacher.serviceYears': 'Hizmet Yılı',
  'teacher.employmentType': 'İstihdam Türü',
  'teacher.nationalId': 'T.C. Kimlik No',
  'school.name': 'Okul Adı',
  'school.code': 'Okul Kodu',
  'school.city': 'İl',
  'school.district': 'İlçe',
  'school.address': 'Okul Adresi',
  'school.principalName': 'Okul Müdürü',
  'document.date': 'Tarih',
  'document.subject': 'Konu',
  'document.number': 'Evrak No',
  'document.description': 'Açıklama',
  'document.startDate': 'Başlangıç Tarihi',
  'document.endDate': 'Bitiş Tarihi',
  'student.fullName': 'Öğrenci Adı Soyadı',
  'student.className': 'Sınıf/Şube',
  'student.schoolNumber': 'Okul No',
  'student.birthDate': 'Doğum Tarihi',
  'student.address': 'Öğrenci Adresi',
  'student.academicNotes': 'Akademik Bilgiler',
  'student.socialNotes': 'Sosyal / Davranışsal Gözlemler',
  'student.interests': 'İlgi Alanları',
  'student.specialNotes': 'Özel Notlar',
  'student.strengths': 'Güçlü Yönleri',
  'student.supportNeeds': 'Desteklenmesi Gereken Alanlar',
  'student.observations': 'Akademik / Sosyal Gözlemler',
  'parent.fullName': 'Veli Adı Soyadı',
  'parent.phone': 'Veli Telefon',
  'meeting.date': 'Toplantı Tarihi',
  'meeting.time': 'Toplantı Saati',
  'meeting.location': 'Toplantı Yeri',
  'meeting.topic': 'Toplantı Konusu',
  'meeting.decisions': 'Alınan Kararlar',
  'meeting.notes': 'Görüşme/Toplantı Notları',
  'meeting.followUp': 'Alınan Kararlar / Takip',
  'meeting.method': 'Görüşme Şekli',
  'meeting.teacherName': 'Görüşülen Öğretmen',
  'meeting.teacherBranch': 'Görüşülen Öğretmenin Branşı',
  'meeting.studentStatement': 'Öğrencinin İfadesi / Görüşü',
  'meeting.teacherObservation': 'Öğretmen Gözlemi',
  'leave.reason': 'İzin Gerekçesi',
  'leave.startDate': 'İzin Başlangıç Tarihi',
  'leave.endDate': 'İzin Bitiş Tarihi',
  'leave.dayCount': 'İzin Gün Sayısı',
  'leave.address': 'İzin Adresi',
  'leave.attachments': 'Ekler',
  'leave.dailyTimeRange': 'Günlük Saat Aralığı',
  'leave.notes': 'Açıklama',
  'lesson.subject': 'Ders Adı',
  'lesson.gradeLevel': 'Sınıf/Şube',
  'lesson.topic': 'Konu',
  'plan.content': 'Konular ve Kazanımlar',
  'plan.period': 'Dönem',
  'plan.activities': 'Faaliyetler',
  'academic.year': 'Eğitim Öğretim Yılı',
  'classroom.room': 'Derslik',
  'classroom.name': 'Şube',
  'seatingPlan': 'Oturma Düzeni',
  'dutySchedule': 'Görev Dağılımı',
  'zumreMembers': 'Katılımcılar',
  'agendaItems': 'Gündem Maddeleri',
  'decisions': 'Kararlar',
  'parentAttendees': 'Katılan Veliler',
  'bepMembers': 'BEP Geliştirme Birimi Katılımcıları',
  'decisionTracking': 'Karar Takip Listesi',
  'branchTeachers': 'Katılımcı Öğretmenler',
  'studentNotes': 'Öğrenci / Sınıf Değerlendirmeleri',
  'bep.course': 'Ders / Alan',
  'bep.currentPerformance': 'Performans Düzeyi / Başlangıç Durumu',
  'bep.methodsAndAssessment': 'Yöntem / Materyal / Değerlendirme',
  'bep.longTermGoals': 'Uzun Dönemli Amaçlar',
  'bep.shortTermGoals': 'Kısa Dönemli Amaçlar ve Ölçütler',
  'bep.teamMembers': 'BEP Geliştirme Birimi',
  'exam.className': 'Sınıf / Şube',
  'exam.name': 'Sınav Adı',
  'exam.date': 'Sınav Tarihi',
  'exam.studentCount': 'Öğrenci Sayısı',
  'exam.average': 'Sınıf Ortalaması',
  'exam.analysisItems': 'Kazanım / Soru Bazlı Değerlendirme',
  'exam.actions': 'Alınacak Önlemler',
  'activity.name': 'Etkinlik Adı',
  'activity.date': 'Etkinlik Tarihi',
  'activity.location': 'Etkinlik Yeri',
  'activity.notes': 'Açıklama / Özel Durum',
  'bank.name': 'Banka',
  'bank.iban': 'IBAN',
  'payroll.monthYear': 'Ay / Yıl',
  'payroll.totalExtraHours': 'Toplam Ek Ders Saati',
  'payroll.weeklyLessonHours': 'Haftalık Ders Saati',
  'payroll.dutyHours': 'Nöbet Saati',
  'payroll.otherHours': 'Diğer Saatler',
  'payroll.entries': 'Haftalık / Günlük Dağılım',
  'payroll.notes': 'Kontrol Notu',
  'payroll.missingHours': 'Eksik Saat',
  'payroll.attachments': 'Ekler',
  'request.assignmentReason': 'Görevlendirme Gerekçesi',
  'request.assignmentPlace': 'Görevlendirilecek Kurum/Alan',
  'request.startDate': 'Görevlendirme Başlangıç Tarihi',
  'request.endDate': 'Görevlendirme Bitiş Tarihi',
  'request.notes': 'Ek/Açıklama',
};

String fieldLabel(String key) => _fieldLabels[key] ?? key;
